### ISSUE TITLE
[SDK-Version] 1.8 Pull Message

### ISSUE THREAD

**Issue by BY-AJ** [cometchat-pro/android-chat-sdk#18]
**Describe the bug**
When pulling the message,return fetching failed with exception: Request Already in Progress

![158221f9b4000510bef6b84177d3970](https://user-images.githubusercontent.com/32251261/68259247-5164fa80-0074-11ea-95e5-72bf36993c1b.png)

**Comment by adityagokula2210** [comment]
Hello @BY-AJ 
Apologies for the late reply. This is the default behavior of the SDK. Since while fetching messages there is pagination involved, we cannot let two requests to be executed simultaneously. Thus, if a request to fetch messages is already in progress, the SDK returns the exception saying request already in progress. You can ignore this exception and call the fetchNext() or fetchPrevious() method again if this exception is encountered.
Hope this helps.
