### ISSUE TITLE
Could not run on android studio

### ISSUE THREAD

**Issue by rolandgerges** [cometchat-pro/android-chat-sdk#38]
Trying to run this project on android studio and receiving the below error:
_Could not GET 'https://dl.bintray.com/cometchat/pro/com/cometchat/pro-android-chat-sdk/2.2.1/pro-android-chat-sdk-2.2.1.pom'. Received status code 403 from server: Forbidden_
_Could not HEAD 'https://dl.bintray.com/cometchat/pro/com/cometchat/pro-android-calls-sdk/2.1.1/pro-android-calls-sdk-2.1.1.pom'. Received status code 403 from server: Forbidden_

------
Build.gradle:
dependencies {
   implementation 'com.cometchat:pro-android-chat-sdk:2.2.1'
   implementation 'com.cometchat:pro-android-calls-sdk:2.1.1'
}

**Comment by adityagokula2210** [comment]
Hello @rollyy 
Due to the shutdown of Bintray services, we had to move the Maven repository where the CometChat Android SDKs were hosted to a new one. Thus, the versions of the Android SDK below 2.3.0 are not available anymore. 
I would suggest you try using the latest version of the Android SDK (2.4.1). Also, you will need to change the URL of the maven repository in the project level Gradle file of your project from

https://dl.bintray.com/cometchat/pro

to 

https://dl.cloudsmith.io/public/cometchat/cometchat-pro-android/maven/

Please do let us know if making the above changes solves the problem for you. In case you are still facing any issues please do let us know and we will be happy to help you out

Thanks
